### PR TITLE
Example script for showing flag on slack status

### PR DESCRIPTION
**Pull request by hawkz**

### CODE REVIEW

**Review by tomkins — CHANGES_REQUESTED** [review]
Have a look at: http://slackapi.github.io/python-slackclient/real_time_messaging.html#rtm-events

And have a look at: https://api.slack.com/rtm#events

Could you improve the script so it uses the events API instead of calling Slack every second? It's a bit abusive.

**Comment by hawkz** [comment]
image
Tested via webcam (spot the green dot!)

**Comment by richpeters** [comment]
Haha this is a very smart clever system

**Review by tomkins — APPROVED** [review]
Works nicely!

**Pull request merged**
